### ISSUE TITLE
Dragino Lora Shield

### ISSUE THREAD

**Issue by Hermanverschooten** [brunosantanaa/Elixir-LoRa#1]
I am trying out your library with a Dragino Lora Shield, but it fails on checking the version.

**Comment by brunosantanaa** [comment]
This can occur because there is no SPI communication.
Are you using the LoRa GPS Hat shield?
I verified that he does not use pins CE0/CE1 (GPIO8/7) of the raspberry. Using GPIO25 for this function.
Could you check?

**Comment by brunosantanaa** [comment]
@Hermanverschooten This can occur because there is no SPI communication.
Are you using the LoRa GPS Hat shield?
I verified that it does not use pins CE0/CE1 (GPIO8/7) of the raspberry. Using GPIO25 for this function.
Could you check?

**Comment by Hermanverschooten** [comment]
I am using the LoRa Shield, v1.4 (https://wiki.dragino.com/index.php?title=Lora_Shield)
I have it wired as  explained here https://www.mobilefish.com/developer/lorawan/lorawan_quickguide_build_lora_gateway.html, and ran the program mentioned from raspbian, it gave me output so that seems to confirm the wiring is as it should be. 
What I want to do is just communicate with the same shield on an Arduino Uno to toggle a relay from a distance.

**Comment by brunosantanaa** [comment]
You could do the following:

|Name| Dragino Pin | Rasp Pin|
|----|---------|-----------|
|MISO| 33 | 21 |
|MOSI| 37 | 19 |
|SCK| 34 | 23 |
|**NSS**| 10 | **24** |
|RST| SV 7 | 11 |

(it is important to note that in this tutorial you are following the GPIO pins are named using the WiringPi standard, while here we use the BCM standard - https://www.raspberrypi.org/documentation/usage/gpio/)

With this wiring, you can start by configuring only the reset pin, like this:

```elixir
{:ok, pid} = LoRa.start_link([rst: 17])
LoRa.begin(pid, 868.1e6)
```

**Comment by Hermanverschooten** [comment]
That returns `:ok` now, 👍 

Just another question, the LMIC Arduino `raw` sketch is setting
```C
  // Use a frequency in the g3 which allows 10% duty cycling.
  LMIC.freq = 869525000;
  // Maximum TX power
  LMIC.txpow = 27;
  // Use a medium spread factor. This can be increased up to SF12 for
  // better range, but then the interval should be (significantly)
  // lowered to comply with duty cycle limits as well.
  LMIC.datarate = DR_SF9;
  // This sets CR 4/5, BW125 (except for DR_SF7B, which uses BW250)
  LMIC.rps = updr2rps(LMIC.datarate);
```
I tried this:

```elixir
    {:ok, pid} = LoRa.start_link(rst: 17)
    LoRa.begin(pid, 869525000)
    LoRa.set_spreading_factor(pid, 9)
    LoRa.set_signal_bandwidth(pid, 125000)
```
And then tried to `send` some text, but the Arduino sees nothing arriving.
I see no messages arriving either.

**Comment by brunosantanaa** [comment]
I haven't used LMIC yet 😕 
But for your application you can test the following code on Arduino:
```c++
#include <SPI.h>
#include <LoRa.h>

void setup() {
  Serial.begin(9600);
  while (!Serial);

  Serial.println("LoRa Receiver");

  if (!LoRa.begin(869.525E6)) {
    Serial.println("Starting LoRa failed!");
    while (1);
  }
  LoRa.setSpreadingFactor(9);
  LoRa.setSignalBandwidth(125E3);
}

void loop() {
  // try to parse packet
  int packetSize = LoRa.parsePacket();
  if (packetSize) {
    // received a packet
    Serial.print("Received packet '");

    // read packet
    while (LoRa.available()) {
      Serial.print((char)LoRa.read());
    }

    // print RSSI of packet
    Serial.print("' with RSSI ");
    Serial.println(LoRa.packetRssi());
  }
}
```
and on rasp:
```elixir
{:ok, pid} = LoRa.start_link(rst: 17)
LoRa.begin(pid, 869.525e6)
LoRa.set_spreading_factor(pid, 9)
LoRa.set_signal_bandwidth(pid, 125.0e3)
LoRa.send(pid, "test")
```
